// File generated by manual override
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:123456789:web:dummy',
    messagingSenderId: '123456789',
    projectId: 'pricebuddy-5a869',
    authDomain: 'pricebuddy-5a869.firebaseapp.com',
    storageBucket: 'pricebuddy-5a869.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:123456789:ios:dummy',
    messagingSenderId: '123456789',
    projectId: 'pricebuddy-5a869',
    storageBucket: 'pricebuddy-5a869.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:123456789:android:dummy',
    messagingSenderId: '123456789',
    projectId: 'pricebuddy-5a869',
    storageBucket: 'pricebuddy-5a869.appspot.com',
  );
  
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:123456789:ios:dummy',
    messagingSenderId: '123456789',
    projectId: 'pricebuddy-5a869',
    storageBucket: 'pricebuddy-5a869.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
